# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2017-08-28 18:54
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('quote_app', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='quote',
            name='user_id',
            field=models.IntegerField(default=0),
            preserve_default=False,
        ),
    ]
