# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2017-08-28 19:30
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('quote_app', '0002_quote_user_id'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='quote',
            name='user_id',
        ),
    ]
