# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2017-08-28 18:14
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('quote_app', '0001_initial'),
        ('login_app', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='quote_own',
            field=models.ManyToManyField(related_name='quoter', to='quote_app.Quote'),
        ),
    ]
